#pragma config(Sensor, dgtl12, green,          sensorLEDtoVCC)
#pragma config(Motor,  port2,           rightMotor,    tmotorVex269_MC29, openLoop)
#pragma config(Motor,  port3,           leftMotor,     tmotorVex269_MC29, openLoop)
#pragma config(Motor,  port9,           servoMotor,    tmotorServoStandard, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
  Project Title: A3_1_2_Part1
  Team Members:
  Date:
  Section:


  Task Description:


  Pseudocode:

*/

task main()
{
turnLEDOff(green);
wait(1);
turnLEDOn(green);
wait(1);
turnLEDOff(green);
wait(1);
turnLEDOn(green);
wait(1);
turnLEDOff(green);




}
