#pragma config(Sensor, dgtl12, green,          sensorLEDtoVCC)
#pragma config(Motor,  port2,           rightMotor,    tmotorVex269_MC29, openLoop)
#pragma config(Motor,  port3,           leftMotor,     tmotorVex269_MC29, openLoop)
#pragma config(Motor,  port9,           servoMotor,    tmotorServoStandard, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
  Project Title: A3_1_2_Part1
  Team Members: Teruhiro, Ryan, Christian, Andrew
  Date: 2/11/19
  Section: N/A


  Task Description:


  Pseudocode:

*/

task main()
{
startMotor(rightMotor, 63);
wait(5);
stopMotor(rightMotor);
startMotor(leftMotor, -95);
wait(2.5);
stopMotor(rightMotor);
startMotor(rightMotor, 127);
startMotor(leftMotor, 127);
wait(7.25);
stopMotor(rightMotor);
stopMotor(leftMotor);
}
