#pragma config(Motor,  port3,           wireServo,     tmotorServoStandard, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
Project Title: The Supply Drop
Team Members: Christian Guarin Andrew Chiu Teruhiro Kobayashi Ryan Birmingham
Date: 2/25/2019
Section:


Task Description:


Pseudocode:

*/

task main()
{                                     //Program begins, insert code within curly braces
	setServo(port3,127);
	wait(3);



}
